# Generated by Django 5.1.4 on 2025-09-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AshaWorker',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('assign_to', models.CharField(max_length=50)),
            ],
        ),
    ]
